apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ei-infer-people-app
  labels:
    service-monitor: ei-infer-people-app
spec:
  selector:
    matchLabels:
      app: ei-infer-people-app
  endpoints:
  - port: web
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ei-infer-face-int8-app
  labels:
    service-monitor: ei-infer-face-int8-app
spec:
  selector:
    matchLabels:
      app: ei-infer-face-int8-app
  endpoints:
  - port: web
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ei-infer-face-fp32-app
  labels:
    service-monitor: ei-infer-face-fp32-app
spec:
  selector:
    matchLabels:
      app: ei-infer-face-fp32-app
  endpoints:
  - port: web
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ei-infer-car-int8-app
  labels:
    service-monitor: ei-infer-car-int8-app
spec:
  selector:
    matchLabels:
      app: ei-infer-car-int8-app
  endpoints:
  - port: web
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ei-infer-car-fp32-app
  labels:
    service-monitor: ei-infer-car-fp32-app
spec:
  selector:
    matchLabels:
      app: ei-infer-car-fp32-app
  endpoints:
  - port: web
    interval: 15s